[package]
name = "cryptoscript"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
enumset = { version = "1.0.8", features = ["serde"] }
generic-array = "0.14"
hex = "0.4"
hex-literal = "0.3"
indexmap = "1.5"
k256 = { version = "0.10.2", features = ["std", "ecdsa", "serde"] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["arbitrary_precision", "preserve_order"] }
sha2 = "0.9"
sha3 = "0.9"
thiserror = "1.0"
typenum = "1.15.0"
