[package]
name = "cryptoscript"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9"
sha3 = "0.9"
hex-literal = "0.3"
generic-array = "0.14"
hex = "0.4"
thiserror = "1.0"
